### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_XUMO#23]
```
version: '2.1'
services:
  fhdhr_xumo:
    image: fhdhr_xumo:0.4.7
    container_name: fhdhr_xumo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900
      - 5004:5004
    volumes:
      - /<docker-config-directory>/fhdhr_xumo:/app/config
    restart: always
```
